# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria'),
            preserve_default=False,
        ),
    ]
