# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_ingrediente_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoingrediente',
            name='ingrediente',
        ),
    ]
