# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_productoingrediente_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoingrediente',
            name='ingrediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Ingrediente'),
            preserve_default=False,
        ),
    ]
